### ISSUE TITLE
JSMin: Unterminated String at byte (even with html param)

### ISSUE THREAD

**Issue by timkelty** [khalwat/minify#6]
Getting this error in production: https://github.com/mrclay/minify/issues/81

However, I'm only using `{%- minify html -%}`, so it shouldn't be touching any JS...

**Comment by john-henry** [comment]
Hi Tim,
are you running SEOmatic too? Try and disable that quickly. I found the same and believe the issue lies with the  Google JSON schema and the minifier. I'm still investigating

**Comment by timkelty** [comment]
@john-henry Indeed I am. I'll give it a shot.

**Comment by khalwat** [comment]
So if you're seeing this, somehow SEOmatic is generating JSON-LD that is invalid.  Which would be really strange, it tries very hard to guard against such things.

Normally it's something like a quote that isn't escaped or such.

What would REALLY help me would be if you could get me the dump of JSON that the minifier is choking on.  What you can do to make this happen is:

Disable Minify

Send me the entire page source used to cause the error so I can look at the generated script tags

If you don't want to post them here, email them to: andrew@nystudio107.com

**Comment by john-henry** [comment]
Came back after my dinner and all seems to be working now. Not sure what has changed. Was happening on local and dev and cache was disabled on local. Ill keep and eye on things but looks to have shook itself out. Thanks

**Comment by khalwat** [comment]
This should be fixed in SEOmatic 1.1.27, which I just pushed:

https://github.com/nystudio107/seomatic

Basically, it was stray control characters (most like \n or \r) in the meta that then was carried into the JSON-LD, and apparently JS-min didn't like it.  That's why it happened for some entries, but not others.

We now strip all control characters from the SEOmatic meta JSON-LD.

Thanks to @timkelty for the help.

**Comment by sulabh** [comment]
I have also run into trouble with JSMin with exact same error on magento2. It does not happen everytime though. It happens at the JSON that I am pushing to GA. But my json is valid. there are no stray characters.

**Comment by thisisjamessmith** [comment]
I also ran into this issue. I'm not using SEOmatic, but was outputting some JSON-LD that contained html tags. Annoyingly, since Minify now defaults `disableDevModeMinifying` to `true`, I didn't catch the error until it was pushed to the remote staging site.

I fixed it by using the `json_encode` twig filter when outputting the relevant json-ld properties.

**Comment by kaspar-allenbach** [comment]
I have this as well and Im on SEOmatic `1.1.56`

**Comment by bymayo** [comment]
This also happens when you have just inline JS in the template also. For me, it was because I had a Vimeo play function that looked like `player.on('play", function() {` which needed to be `player.on('play', function() {`

Just got to check for any minor mistakes in the code, as well as checking SEOMatic JSON

**Comment by khalwat** [comment]
@bymayo Did you mean to post this on the old Craft 2 SEOmatic repo?

**Comment by bymayo** [comment]
WHOOPS. I just came across the issue on Google. My bad.

**Comment by dominikkrulak** [comment]
I too encountered similar issue but not with SEOmatic.
I scraped `<textarea></textarea>` value into JS variable and string had `\n` character. I couldn't remove `\n` because it had to stay in the same text format. I had to find other way to manipulate it.
